"use client";
import {useMemo,useState} from "react";
type Sport="전체"|"축구"|"야구"|"농구"|"배구";
type M={id:number;sport:Exclude<Sport,"전체">;league:string;home:string;away:string;time:string;venue:string};
const I={축구:"⚽",야구:"⚾",농구:"🏀",배구:"🏐"};
const DEMO:M[]=[{id:5276,sport:"야구",league:"NPB",home:"요미우리",away:"히로시마",time:"18:00",venue:"도쿄돔"},{id:1001,sport:"축구",league:"축구",home:"서울 FC",away:"부산 FC",time:"18:30",venue:"서울월드컵경기장"},{id:6101,sport:"농구",league:"농구",home:"서울",away:"부산",time:"19:00",venue:"잠실"},{id:7201,sport:"배구",league:"배구",home:"현대",away:"대한",time:"19:00",venue:"인천"}];
function picks(m:M){return m.sport==="야구"?[["일반 승패","홈 승",61.8],["핸디캡 -2.5","원정 +2.5",70.1],["U/O","UNDER",56.1]]:m.sport==="축구"?[["승무패","홈 승",64.2],["핸디캡","원정 +1",67.1],["U/O 2.5","UNDER",55.8]]:m.sport==="농구"?[["승패","홈 승",67.4],["핸디캡","홈 -3.5",58.2],["U/O","UNDER",55.4]]:[["승패","홈 승",68.7],["세트 핸디","홈 -1.5",57.8],["U/O","UNDER",54.9]]}
export default function Home(){
 const[sport,setSport]=useState<Sport>("전체"),[active,setActive]=useState(5276),[selected,setSelected]=useState<number[]>([5276]),[status,setStatus]=useState("준비"),[matched,setMatched]=useState<any>(null);
 const list=useMemo(()=>DEMO.filter(x=>sport==="전체"||x.sport===sport),[sport]),m=DEMO.find(x=>x.id===active)!; const ps=picks(m),best=Math.max(...ps.map(x=>x[2] as number));
 async function collect(){setStatus("실제 경기 매칭 중…");setMatched(null);try{const map:any={축구:"football",야구:"baseball",농구:"basketball",배구:"volleyball"};const r=await fetch(`/api/match?home=${encodeURIComponent(m.home)}&away=${encodeURIComponent(m.away)}&sport=${map[m.sport]}`);const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||"경기 매칭 실패");setMatched(j);setStatus(`실제 경기 매칭 완료 · Fixture #${j.fixtureId} · ${new Date().toLocaleString("ko-KR")}`)}catch(e:any){setStatus(e.message||"수집 실패")}}
 const lineups=matched?.lineups;
 return <main className="app"><div className="top"><div><div className="title">Wisetoto Analyzer · Live Free v2</div><div className="sub">실제 경기 매칭 · 수동 수집 · 테스트 분석</div></div><div className="bar"><b>99회차</b><button className="btn primary" onClick={collect}>🔄 데이터 수집</button><button className="btn light" onClick={()=>alert(selected.length+"개 경기 분석")}>📊 선택 경기 분석</button><span className="small">{status}</span></div></div>
 <div className="tabs">{(["전체","축구","야구","농구","배구"] as Sport[]).map(s=><button key={s} className={"tab "+(sport===s?"active":"")} onClick={()=>setSport(s)}>{s!=="전체"&&I[s]+" "}{s}</button>)}</div>
 <div className="layout"><section className="panel"><h3>경기</h3>{list.map(x=><div key={x.id} className={"match "+(x.id===active?"sel":"")} onClick={()=>setActive(x.id)}><input type="checkbox" checked={selected.includes(x.id)} onChange={e=>setSelected(v=>e.target.checked?[...v,x.id]:v.filter(y=>y!==x.id))} onClick={e=>e.stopPropagation()}/><div className="sport">{I[x.sport]}</div><div className="grow"><b>{x.id} · {x.home} vs {x.away}</b><div className="small">{x.league} · {x.time} · {x.venue}</div></div></div>)}</section>
 <section className="panel"><div className="hero"><div><div className="small">{I[m.sport]} {m.league} · Wisetoto #{m.id}</div><h2>{m.home} vs {m.away}</h2><div className="big">{m.time}</div>{matched&&<div className="ok">✓ SportsAPI Fixture #{matched.fixtureId}로 실제 매칭됨</div>}</div><div className="right"><div className="small">테스트 최고 픽</div><div className="big">{ps.find(x=>x[2]===best)?.[1]}</div><div className="pct">{best}%</div></div></div>
 <div className="cards"><div className="card">데이터 공급원<b>sportsapi</b></div><div className="card">경기 매칭<b>{matched?"완료":"대기"}</b></div><div className="card">라인업<b>{lineups?.confirmed?"확정":"확인 필요"}</b></div></div>
 <div className="section"><h3>게임유형별 최적 픽 <span className="small">※ 데모 확률</span></h3>{ps.map(x=><div className={"pick "+(x[2]===best?"best":"")} key={x[0] as string}><div><b>{x[0]}</b><div className="small">{x[1]}</div></div><div className="pct">{Number(x[2]).toFixed(1)}%</div></div>)}</div>
 {matched&&<div className="section"><h3>수집된 분석 재료</h3><div className="cards"><div className="card">H2H<b>{matched.h2h?"수신":"없음"}</b></div><div className="card">최근 경기<b>{matched.recentSummary?.home?.length||0} / {matched.recentSummary?.away?.length||0}</b></div><div className="card">통계<b>{matched.statistics?"수신":"없음"}</b></div></div></div>}
 {matched&&<div className="section"><h3>실제 매칭 원천 데이터</h3><pre style={{whiteSpace:"pre-wrap",fontSize:12,background:"#f6f8fa",padding:12,borderRadius:10,maxHeight:360,overflow:"auto"}}>{JSON.stringify({fixtureId:matched.fixtureId,fixture:matched.fixture,detail:matched.detail,lineups:matched.lineups,h2h:matched.h2h,recentSummary:matched.recentSummary},null,2)}</pre></div>}
 <div className="notice">이번 버전은 경기번호를 팀명으로 SportsAPI의 안정적인 team ID와 매칭한 뒤 실제 fixture ID를 찾아 상세정보·라인업·통계·H2H·최근경기를 수집합니다. 확률은 아직 데모입니다.</div>
 </section></div></main>}
